<?php
/**
* @file
* Módulo Blocks Forcontu
* Este módulo nos permitirá definir bloques
*/

/**
 * Implements hook_block_info().
 */
function blocks_forcontu_block_info() {
  // Unpublished nodes
  $blocks['unpublished_nodes'] = array(
    'info' => t('Unpublished nodes'),
    'cache' => DRUPAL_NO_CACHE,
  );
  //Users list
  $blocks['users_list'] = array(
    'info' => t('Users list'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function blocks_forcontu_block_configure($delta = '') {
$form = array();
  switch ($delta) {
    case 'unpublished_nodes':
      $form['num_nodes'] = array(
        '#type' => 'select',
        '#title' => t('Select the number of nodes to display in this block.'),
        '#default_value' => variable_get('blocks_forcontu_num_nodes', 3),
        '#options' => array(1 => 1, 2 => 2, 3 => 3, 4 => 4, 5 => 5),
      );
      break;
    case 'users_list':
      $form['num_users'] = array(
        '#type' => 'select',
        '#title' => t('Select the numbers of users to display in this block.'),
        '#default_value' => variable_get('blocks_forcontu_num_users', 3),
        '#options' => array(1 => 1, 2 => 2, 3 => 3, 4 => 4, 5 => 5),
      );
      $form['active_users'] = array(
        '#type' => 'checkbox',
        '#title' => t('Display only active users.'),
        '#default_value' => variable_get('blocks_forcontu_active_users', 0),
      );
      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function blocks_forcontu_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'unpublished_nodes':
      variable_set('blocks_forcontu_num_nodes', $edit['num_nodes']);
      break;
    case 'users_list':
      variable_set('blocks_forcontu_num_users', $edit['num_users']);
      variable_set('blocks_forcontu_active_users', $edit['active_users']);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function blocks_forcontu_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'unpublished_nodes':
      $result = db_select('node', 'n')
        ->fields('n', array('nid', 'title', 'created'))
        ->condition('status', 0)
        ->orderBy('created', 'DESC')
        ->range(0, variable_get('blocks_forcontu_num_nodes', 3))
        ->execute();
      if ($node_title_list = node_title_list($result)) {
        $block['subject'] = t('Unpublished nodes');
        $block['content'] = $node_title_list;
      }
      break;

    case 'users_list':
      $query = db_select('users', 'u')
        ->fields('u', array('uid', 'name' , 'created'))
        ->orderBy('created', 'DESC')
        ->range(0, variable_get('blocks_forcontu_num_users', 3));
      //Comprobamos si sólo hay que mostrar usuarios activos
      if (variable_get('blocks_forcontu_active_users', 3) == 1) {
        $query->condition('status', 1);
      }
      $result = $query->execute();
      $variables['users'] = $result->fetchAll();
      $variables['title'] = NULL;
      $block['subject'] = t('Users list');
      $block['content'] = theme_user_list($variables);
      break;
  }
  return $block;
}